# Generated by Django 6.0 on 2026-01-13 05:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tourdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='itinerary',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
