# Generated by Django 6.0 on 2026-01-15 12:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tourimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='description',
            field=models.TextField(help_text='Short summary for the card view'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration_days',
            field=models.PositiveIntegerField(help_text='Total duration of the trip'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Uncheck to hide this tour from users'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='itinerary',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Detailed day-wise plan', null=True),
        ),
        migrations.AlterField(
            model_name='tourdate',
            name='capacity',
            field=models.PositiveIntegerField(default=20, help_text='Total seats available for this batch'),
        ),
    ]
