"""
Django settings for bondvoyage project.

Generated by 'django-admin startproject' using Django 5.x/6.x.
Refined and Organized for BondVoyage Travel Portal.
"""

import os
from pathlib import Path

# ==========================================
# 1. CORE PROJECT PATHS
# ==========================================
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ==========================================
# 2. SECURITY SETTINGS
# ==========================================
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y@891zc7xa$%mvlx1%5tk_(i=u#sh&+_v1w^!j8pt_&q)70e!k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # Allow all hosts for local development


# ==========================================
# 3. APPLICATION DEFINITION
# ==========================================
INSTALLED_APPS = [
    # Default Django Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.postgres',  # Enabled for advanced DB features

    # Third-Party Apps
    'ckeditor',                 # Rich text editor for descriptions

    # My Custom Apps
    'users',                    # Handles Custom User & Profiles
    'tours',                    # Handles Packages, Destinations & Itineraries
    'bookings',                 # Handles Booking Logic & Payments
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bondvoyage.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Global templates folder
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bondvoyage.wsgi.application'


# ==========================================
# 4. DATABASE (PostgreSQL)
# ==========================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'bondvoyage_db',
        'USER': 'postgres',
        'PASSWORD': 'postgres',  # Ensure this matches your local PGAdmin password
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# ==========================================
# 5. AUTHENTICATION & PASSWORDS
# ==========================================
# Point to our custom user model
AUTH_USER_MODEL = 'users.CustomUser'

AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]

# Redirects after authentication
LOGIN_URL = 'login'              # The URL name for the login page
LOGIN_REDIRECT_URL = 'home'      # Redirect here after successful login
LOGOUT_REDIRECT_URL = 'home'     # Redirect here after logout


# ==========================================
# 6. INTERNATIONALIZATION
# ==========================================
LANGUAGE_CODE = 'en-us'

# Changed to Indian Standard Time (IST) for accurate booking timestamps
TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True
USE_TZ = True


# ==========================================
# 7. STATIC & MEDIA FILES
# ==========================================
# Static files (CSS, JavaScript, Images used by the website design)
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (Images uploaded by users/admins, e.g., Tour Photos)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ==========================================
# 8. OTHER SETTINGS
# ==========================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'