# Generated by Django 6.0 on 2025-12-16 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('tours', '0002_tourdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tour_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tours.tourdate'),
        ),
    ]
