# Generated by Django 6.0 on 2026-01-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_tour_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Payment Reference ID', max_length=100, null=True),
        ),
    ]
