# Generated by Django 6.0 on 2026-01-15 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_payment_status_alter_booking_status'),
        ('tours', '0005_tour_updated_at_alter_tour_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated: Price x People', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours.tour'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour_date',
            field=models.ForeignKey(blank=True, help_text='The specific date batch the user has chosen', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours.tourdate'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Payment Reference ID (e.g., UPI Transaction ID)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
